<script lang="ts">
  import { onMount } from 'svelte';
  import { get, post } from '$lib/api';
  let sources: any[] = $state([]); let releases: any[] = $state([]); let foods: any[] = $state([]); let nutrients: any[] = $state([]); let error = $state(''); let message = $state('');
  let sourceForm: any = $state({ source_code: '', source_name: '', source_type: 'regional_table', publisher: '', source_url: '', citation: '', license_notes: '' });
  let releaseForm: any = $state({ source_uid: '', release_label: '', release_date: '', sha256: '', schema_notes: '' });
  let foodForm: any = $state({ source_release_uid: '', source_food_code: '', food_name: '', local_name: '', food_group: '', country_code: 'NG', preparation_state: '', nutrient_uid: '', value: '', unit: '' });
  async function load() { try { [sources, releases, foods, nutrients] = await Promise.all([get('/api/sources'), get('/api/source-releases'), get('/api/external-foods'), get('/api/ontology')]); error = ''; } catch (e: any) { error = e.message; } }
  async function createSource() { try { await post('/api/sources', sourceForm); message = 'Source registered'; sourceForm = { source_code: '', source_name: '', source_type: 'regional_table', publisher: '', source_url: '', citation: '', license_notes: '' }; await load(); } catch (e: any) { error = e.message; } }
  async function createRelease() { try { await post(`/api/sources/${releaseForm.source_uid}/releases`, releaseForm); message = 'Immutable source release registered'; await load(); } catch (e: any) { error = e.message; } }
  async function createFood() {
    try {
      const components = foodForm.nutrient_uid && foodForm.value !== '' ? [{ canonical_nutrient_uid: foodForm.nutrient_uid, value: Number(foodForm.value), unit: foodForm.unit, value_status: 'reported' }] : [];
      await post('/api/external-foods', { ...foodForm, components }); message = 'External food record added'; foodForm = { source_release_uid: '', source_food_code: '', food_name: '', local_name: '', food_group: '', country_code: 'NG', preparation_state: '', nutrient_uid: '', value: '', unit: '' }; await load();
    } catch (e: any) { error = e.message; }
  }
  function selectNutrient(uid: string) { const nutrient = nutrients.find((item) => item.canonical_nutrient_uid === uid); foodForm.nutrient_uid = uid; foodForm.unit = nutrient?.canonical_unit || ''; }
  onMount(load);
</script>
<div class="page-head"><div><span class="kicker">Evidence registry</span><h1>Sources & provenance</h1><p>Register a source, freeze each imported release, then attach external Nigerian or regional food records to that exact release.</p></div></div>
{#if error}<div class="error" style="margin-bottom:12px">{error}</div>{/if}{#if message}<div class="success" style="margin-bottom:12px">{message}</div>{/if}
<section class="platform-grid">
  <div class="card"><h2>1 · Register source</h2><div class="card-sub">Citation, publisher, URL and licence remain part of the evidence record.</div><div class="form-grid"><div class="field"><label>Code <input bind:value={sourceForm.source_code} /></label></div><div class="field"><label>Type <select bind:value={sourceForm.source_type}><option value="regional_table">Regional table</option><option value="food_composition_table">Food composition table</option><option value="study_analysis">Study analysis</option><option value="retention_table">Retention table</option><option value="literature">Literature</option><option value="manual">Manual</option></select></label></div><div class="field span-2"><label>Name <input bind:value={sourceForm.source_name} /></label></div><div class="field"><label>Publisher <input bind:value={sourceForm.publisher} /></label></div><div class="field"><label>URL <input bind:value={sourceForm.source_url} /></label></div><div class="field span-2"><label>Citation <textarea bind:value={sourceForm.citation}></textarea></label></div><div class="field span-2"><label>Licence / use notes <textarea bind:value={sourceForm.license_notes}></textarea></label></div></div><div class="panel-actions"><button class="btn" onclick={createSource}>Register source</button></div></div>
  <div class="card"><h2>2 · Freeze source release</h2><div class="card-sub">A checksum is recommended for imported files.</div><div class="form-grid"><div class="field span-2"><label>Source <select bind:value={releaseForm.source_uid}><option value="">Select source</option>{#each sources as source}<option value={source.source_uid}>{source.source_name}</option>{/each}</select></label></div><div class="field"><label>Release label <input bind:value={releaseForm.release_label} /></label></div><div class="field"><label>Release date <input type="date" bind:value={releaseForm.release_date} /></label></div><div class="field span-2"><label>SHA-256 <input class="mono" bind:value={releaseForm.sha256} /></label></div><div class="field span-2"><label>Schema notes <textarea bind:value={releaseForm.schema_notes}></textarea></label></div></div><div class="panel-actions"><button class="btn" onclick={createRelease}>Add release</button></div></div>
  <div class="card"><h2>3 · Add external food</h2><div class="card-sub">One component can be entered here; bulk pipelines can append the full composition table.</div><div class="form-grid"><div class="field span-2"><label>Source release <select bind:value={foodForm.source_release_uid}><option value="">Select release</option>{#each releases as release}<option value={release.source_release_uid}>{release.source_name} · {release.release_label}</option>{/each}</select></label></div><div class="field"><label>Source food code <input bind:value={foodForm.source_food_code} /></label></div><div class="field"><label>Country <input bind:value={foodForm.country_code} /></label></div><div class="field span-2"><label>Food name <input bind:value={foodForm.food_name} /></label></div><div class="field"><label>Local name <input bind:value={foodForm.local_name} /></label></div><div class="field"><label>Food group <input bind:value={foodForm.food_group} /></label></div><div class="field"><label>Initial nutrient <select value={foodForm.nutrient_uid} onchange={(event) => selectNutrient(event.currentTarget.value)}><option value="">No component yet</option>{#each nutrients as n}<option value={n.canonical_nutrient_uid}>{n.display_name}</option>{/each}</select></label></div><div class="field"><label>Value <input type="number" bind:value={foodForm.value} /></label></div><div class="field"><label>Reported unit <input bind:value={foodForm.unit} placeholder="Set from canonical nutrient" /></label></div></div><div class="panel-actions"><button class="btn" onclick={createFood}>Add external food</button></div></div>
</section>
<div class="card" style="margin-top:18px"><div class="split"><div><h2>External food catalogue</h2><div class="card-sub">{foods.length} project records</div></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Source code</th><th>Name</th><th>Local name</th><th>Group</th><th>Release</th><th>Components</th></tr></thead><tbody>{#each foods as food}<tr><td class="mono">{food.source_food_code}</td><td>{food.food_name}</td><td>{food.local_name || '—'}</td><td>{food.food_group || '—'}</td><td>{food.source_name} · {food.release_label}</td><td>{food.component_count}</td></tr>{/each}</tbody></table></div></div>
