<script lang="ts">
 import {onMount} from 'svelte'; import {get,post} from '$lib/api';
 let participants:any[]=$state([]),foods:any[]=$state([]),recalls:any[]=$state([]),error=$state(''),result:any=$state(null);
 let form:any=$state({participant_uid:'',recall_date:'',day_name:'',meal_context:'',notes:'',status:'complete'}); let items:any[]=$state([{food_uid:'',amount_g:'',meal_label:''}]);
 async function load(){try{[participants,foods,recalls]=await Promise.all([get('/api/participants?limit=500'),get('/api/foods?limit=500'),get('/api/recalls?limit=50')])}catch(e:any){error=e.message}}
 function add(){items=[...items,{food_uid:'',amount_g:'',meal_label:''}]}; function remove(i:number){items=items.filter((_,x)=>x!==i)}
 async function save(){error='';try{result=await post('/api/recalls',{...form,items:items.map(i=>({...i,amount_g:Number(i.amount_g)}))});items=[{food_uid:'',amount_g:'',meal_label:''}];await load()}catch(e:any){error=e.message}}
 const visibleResults=()=>result?.results?.filter((r:any)=>r.display_name!=='Calories')||[];
 onMount(load);
</script>
<div class="page-head"><div><span class="kicker">Normalized source events</span><h1>Recall entry</h1><p>Capture food and gram-weight events directly. Derived nutrient totals are reproducible from the composition version snapshot rather than cached Java BLOBs.</p></div></div>
{#if error}<div class="error" style="margin-bottom:12px">{error}</div>{/if}
<div class="grid-2"><div class="card"><h2>New dietary recall</h2><div class="card-sub">Research Core calculation · per-100 g composition basis</div><div class="form-grid"><div class="field span-2"><label>Participant <select bind:value={form.participant_uid}><option value="">Select participant…</option>{#each participants as p}<option value={p.participant_uid}>{p.participant_code}</option>{/each}</select></label></div><div class="field"><label>Recall date <input type="date" bind:value={form.recall_date}/></label></div><div class="field"><label>Day label <select bind:value={form.day_name}><option value="">—</option>{#each ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'] as d}<option>{d}</option>{/each}</select></label></div><div class="field"><label>Meal context <input bind:value={form.meal_context} placeholder="Optional"/></label></div><div class="field"><label>Status <select bind:value={form.status}><option>complete</option><option>draft</option></select></label></div></div>
<div style="margin-top:18px"><div class="split"><h2>Foods consumed</h2><button class="btn secondary small" onclick={add}>＋ Add row</button></div>{#each items as item,i}<div class="form-grid" style="margin-top:9px;grid-template-columns:2fr 1fr 1fr auto"><div class="field"><label>Food <select bind:value={item.food_uid}><option value="">Select food…</option>{#each foods as f}<option value={f.food_uid}>{f.legacy_food_id} · {f.food_name}</option>{/each}</select></label></div><div class="field"><label>Amount (g) <input type="number" min="0" step="any" bind:value={item.amount_g}/></label></div><div class="field"><label>Meal label <input bind:value={item.meal_label}/></label></div><button class="close" style="align-self:end" aria-label="Remove item" onclick={()=>remove(i)}>×</button></div>{/each}</div>
<div class="notice" style="margin-top:16px">The interactive platform is a research record system. It does not provide personalized weight-loss or calorie-restriction guidance.</div><div class="panel-actions"><button class="btn" onclick={save}>Save & calculate research record</button></div></div>
<div class="card"><h2>Calculated research snapshot</h2><div class="card-sub">Minerals, toxicants and other available composition values</div>{#if result}<div class="component-grid">{#each visibleResults().slice(0,36) as r}<div class="component"><span class="component-label">{r.display_name}</span><b>{Number(r.value).toFixed(3)} {r.unit}</b><br/><span class="tag">{r.component_group}</span></div>{/each}</div>{:else}<div class="empty">Save a recall to create a version-linked composition snapshot.</div>{/if}</div></div>
<div class="card" style="margin-top:18px"><div class="split"><div><h2>Recent normalized recalls</h2><div class="card-sub">New platform records only; historical Java recalls remain evidence.</div></div><span class="status neutral">{recalls.length} shown</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Participant</th><th>Date</th><th>Day</th><th>Foods</th><th>Mode</th><th>Status</th></tr></thead><tbody>{#each recalls as r}<tr><td class="mono">{r.participant_code}</td><td>{r.recall_date||'—'}</td><td>{r.day_name||'—'}</td><td>{r.item_count}</td><td><span class="tag">{r.calculation_mode}</span></td><td><span class="status">{r.status}</span></td></tr>{/each}</tbody></table></div></div>

