<script lang="ts">
  let selected = $state('collection');
  const areas = [
    { id: 'collection', label: 'Research data', code: 'RD', title: 'A structured operational record for each study.', copy: 'Manage foods, participants, experiments and multi-day recall entries inside a named project space. Single-entry forms and staged batch imports share the same validation and audit contract.', items: ['Sequential research IDs', 'CSV and flat-sheet XLSX staging', 'Atomic commit or complete rollback', 'Versioned edits and append-only audit'] },
    { id: 'composition', label: 'Composition', code: 'FC', title: 'A separate evidence layer for food composition.', copy: 'Canonical nutrients, explicit units and source releases provide a stable vocabulary without silently correcting legacy results or filling gaps.', items: ['Canonical nutrient ontology', 'FAO/INFOODS reference metadata', 'Source release and licence records', 'Reviewed food-match candidates'] },
    { id: 'recipes', label: 'Recipes', code: 'RE', title: 'Recipe calculations with visible assumptions.', copy: 'Model ingredients, edible fractions, final cooked yield and nutrient retention while recording the exact inputs used for each saved result.', items: ['Ingredient contribution lineage', 'Yield-factor calculation', 'Retention-factor provenance', 'Strict missing-value handling'] },
    { id: 'analytics', label: 'Analytics', code: 'AN', title: 'Descriptive analysis before machine learning.', copy: 'Run privacy-aware cohort summaries and quality-control flags. Models assist review queues; they do not invent chemistry, merge foods or make clinical decisions.', items: ['Minimum-group suppression', 'Recorded-day participant means', 'Median/MAD quality flags', 'Specialist-approved match triage'] }
  ];
  const current = $derived(areas.find((area) => area.id === selected) || areas[0]);
</script>
<svelte:head><title>Capabilities · Dietary Recall</title></svelte:head>
<section class="public-page-intro"><span class="public-eyebrow">Platform capabilities</span><h1>A scientific workspace,<br/>not a wall of tools.</h1><p>Each capability sits inside a governed research sequence: establish the record, preserve evidence, review assumptions, then calculate.</p></section>
<section class="capability-explorer"><div class="capability-tabs" role="tablist" aria-label="Capability areas">{#each areas as area}<button class:active={selected === area.id} role="tab" aria-selected={selected === area.id} onclick={() => (selected = area.id)}><span>{area.code}</span>{area.label}</button>{/each}</div><article class="capability-detail"><div class="capability-code">{current.code}</div><div><span class="public-eyebrow">{current.label}</span><h2>{current.title}</h2><p>{current.copy}</p><ul>{#each current.items as item}<li><i>✓</i>{item}</li>{/each}</ul></div></article></section>
<section class="public-section boundary-grid"><article><span>LEGACY</span><h2>Compatibility stays explicit.</h2><p>Java-era formulas and known quirks are reproduced in a labelled lane so historical outputs remain explainable.</p></article><article><span>VALIDATED</span><h2>Corrections require evidence.</h2><p>Modern units, food matches and retention factors are additive records with provenance and review status.</p></article><article><span>ANALYTICS</span><h2>Models support judgement.</h2><p>Quality flags and candidate ranking guide review; they never generate missing nutrient values or clinical advice.</p></article></section>
