<script lang="ts">
  import { base } from '$app/paths';
  let activeStep = $state(0);
  const workflow = [
    { code: '01', title: 'Capture', heading: 'Structure the study before analysis.', copy: 'Create project spaces, assign research roles, register participants and enter recalls without changing the historical evidence database.', list: ['Food and participant managers', 'Single-entry and CSV/XLSX workflows', 'Project-scoped contributor roles'] },
    { code: '02', title: 'Harmonize', heading: 'Make nutrient evidence comparable.', copy: 'Map legacy components into a canonical ontology while retaining units, source releases, preparation state and every provisional decision.', list: ['Canonical nutrient definitions', 'Unit-aware composition records', 'Candidate-only food matching'] },
    { code: '03', title: 'Review', heading: 'Keep scientific judgement visible.', copy: 'Route mappings, source releases and retention factors through explicit review instead of silently mixing inferred and measured evidence.', list: ['Specialist review queue', 'Append-only provenance events', 'Immutable source snapshot boundary'] },
    { code: '04', title: 'Analyze', heading: 'Reproduce every result.', copy: 'Run portion calculations, cohort descriptives and quality-control checks against a recorded project snapshot with suppression safeguards.', list: ['Legacy parity calculations', 'Privacy-aware cohort descriptives', 'Review-only anomaly flags'] }
  ];
</script>

<svelte:head><title>Dietary Recall · Research platform for Nigerian prepared foods</title><meta name="description" content="A governed research platform for Nigerian prepared-food composition, dietary recall, provenance and reproducible analysis." /></svelte:head>

<section class="public-hero">
  <div class="hero-copy"><span class="public-eyebrow"><i></i>Nigerian prepared-food research</span><h1>Dietary evidence,<br/><em>made traceable.</em></h1><p>Move from prepared-food records and participant recalls to reviewable nutrient evidence and reproducible analysis—without rewriting the original PhD research history.</p><div class="hero-actions"><a class="public-button primary" href={`${base}/projects`}>Open the research demo <span>→</span></a><a class="public-button quiet" href={`${base}/features`}>Explore the scientific workflow</a></div><div class="hero-boundary"><span>✓ Historical source remains immutable</span><span>✓ Synthetic public demo</span><span>✓ Missing values stay missing</span></div></div>
  <div class="hero-instrument" aria-label="Illustration of a governed nutrient evidence record"><div class="instrument-grid"></div><div class="instrument-header"><span>Composition evidence / sample 1002</span><b>REVIEWABLE</b></div><div class="sample-title"><span>Prepared food</span><strong>Illustrative bean porridge</strong><small>Demonstration record · Nigeria · cooked</small></div><div class="sample-reading"><div><span>Canonical component</span><b>Iron</b></div><strong>—</strong><small>missing · no imputation</small></div><div class="sample-reading accent"><div><span>Measured component</span><b>Protein</b></div><strong>12.4</strong><small>g / 100 g · synthetic</small></div><div class="instrument-trace"><span></span><i></i><span></span><i></i><span></span><small>source</small><small>mapping</small><small>review</small></div><div class="instrument-note">Illustrative values only. The public demo contains no participant or licensed composition data.</div></div>
</section>
<section class="trust-strip" aria-label="Scientific design commitments"><span>Immutable evidence boundary</span><i></i><span>Project-scoped collaboration</span><i></i><span>Explicit provenance</span><i></i><span>Reproducible calculations</span></section>
<section class="public-section workflow-section"><div class="section-heading"><span class="public-eyebrow">From record to result</span><h2>One governed workflow.<br/>Four visible stages.</h2><p>The platform separates data capture, scientific interpretation and analysis so each decision can be inspected on its own terms.</p></div><div class="workflow-layout"><div class="workflow-tabs" role="tablist" aria-label="Research workflow stages">{#each workflow as step, index}<button class:active={activeStep === index} role="tab" aria-selected={activeStep === index} onclick={() => (activeStep = index)}><span>{step.code}</span><b>{step.title}</b><i>→</i></button>{/each}</div><article class="workflow-panel" aria-live="polite"><span class="panel-index">{workflow[activeStep].code}</span><div><span class="public-eyebrow">{workflow[activeStep].title}</span><h3>{workflow[activeStep].heading}</h3><p>{workflow[activeStep].copy}</p><ul>{#each workflow[activeStep].list as item}<li>{item}</li>{/each}</ul></div></article></div></section>
<section class="public-section evidence-section"><div class="evidence-copy"><span class="public-eyebrow">Designed for the research record</span><h2>Measured, calculated and provisional values do not become the same thing.</h2><p>Every nutrient value stays connected to its evidence lane, unit, food basis, source release and review state. A calculation can consume evidence; it cannot erase where that evidence came from.</p><a href={`${base}/features`}>Read the scientific capability map <span>→</span></a></div><div class="evidence-lanes"><div><span>01</span><b>Historical evidence</b><p>Read-only Java-era source and explicit compatibility calculations.</p><i class="amber"></i></div><div><span>02</span><b>Research core</b><p>Versioned foods, participants, experiments, recalls and imports.</p><i></i></div><div><span>03</span><b>Validated research</b><p>Ontology, provenance, recipes, retention and reviewed mappings.</p><i></i></div></div></section>
<section class="public-cta"><div><span class="public-eyebrow">A lightweight demonstration</span><h2>Walk through the platform with synthetic records.</h2><p>Create, import, calculate and review. The demo resets when its free service restarts, and it never contains the original PhD participant data.</p></div><a class="public-button light" href={`${base}/projects`}>Enter the demo workspace <span>→</span></a></section>
