<script lang="ts">
  import { base } from '$app/paths';
  let activeStep = $state(0);
  const workflow = [
    { code: '01', title: 'Capture', heading: 'Structure the study before analysis.', copy: 'Create project spaces, assign research roles, register participants and enter recalls without changing the historical evidence database.', list: ['Food and participant managers', 'Single-entry and CSV/XLSX workflows', 'Project-scoped contributor roles'] },
    { code: '02', title: 'Harmonize', heading: 'Make nutrient evidence comparable.', copy: 'Map legacy components into a canonical ontology while retaining units, source releases, preparation state and every provisional decision.', list: ['Canonical nutrient definitions', 'Unit-aware composition records', 'Candidate-only food matching'] },
    { code: '03', title: 'Review', heading: 'Keep scientific judgement visible.', copy: 'Route mappings, source releases and retention factors through explicit review instead of silently mixing inferred and measured evidence. Independent decisions require separately verified accounts and are not completed inside the single-account public demo.', list: ['Review-case contract', 'Append-only provenance events', 'Immutable source snapshot boundary'] },
    { code: '04', title: 'Calculate', heading: 'Scale what is actually stored.', copy: 'Calculate a selected food amount directly, save participant recalls, or run data-dependent descriptives. Missing nutrients remain missing.', list: ['Food amount × per-100 g composition', 'Version-linked recall snapshots', 'Privacy-aware cohort descriptives'] }
  ];
</script>

<svelte:head><title>Dietary Recall · Research platform for Nigerian prepared foods</title><meta name="description" content="A governed research platform for Nigerian prepared-food composition, dietary recall, provenance and reproducible analysis." /></svelte:head>

<section class="public-hero">
  <div class="hero-copy"><span class="public-eyebrow"><i></i>Nigerian prepared-food research</span><h1>Dietary evidence,<br/><em>made traceable.</em></h1><p>Record foods and gram weights, scale the composition values that actually exist, and preserve every source and missing value—without rewriting the original PhD research history.</p><div class="hero-actions"><a class="public-button primary" href={`${base}/calculator`}>Try the composition calculator <span>→</span></a><a class="public-button quiet" href={`${base}/features`}>See what the build supports</a></div><div class="hero-boundary"><span>✓ Historical source remains immutable</span><span>✓ Synthetic public demo</span><span>✓ Missing values stay missing</span></div></div>
  <div class="hero-instrument" aria-label="Illustration of the portion-scaling calculation"><div class="instrument-grid"></div><div class="instrument-header"><span>Composition preview / current project</span><b>NOT SAVED</b></div><div class="sample-title"><span>Calculation</span><strong>Food portion scaling</strong><small>Selected food · selected gram amount</small></div><div class="sample-reading"><div><span>Stored basis</span><b>Component value</b></div><strong>100</strong><small>per 100 g</small></div><div class="sample-reading accent"><div><span>Selected portion</span><b>Gram weight</b></div><strong>N</strong><small>scale factor N ÷ 100</small></div><div class="instrument-trace"><span></span><i></i><span></span><i></i><span></span><small>food</small><small>grams</small><small>result</small></div><div class="instrument-note">The demo contains synthetic foods and participants only. It contains no original participant records or licensed composition dataset.</div></div>
</section>
<section class="trust-strip" aria-label="Scientific design commitments"><span>Immutable evidence boundary</span><i></i><span>Project-scoped collaboration</span><i></i><span>Explicit provenance</span><i></i><span>Reproducible calculations</span></section>
<section class="public-section workflow-section"><div class="section-heading"><span class="public-eyebrow">From record to result</span><h2>One governed workflow.<br/>Four visible stages.</h2><p>The platform separates data capture, scientific interpretation and analysis so each decision can be inspected on its own terms.</p></div><div class="workflow-layout"><div class="workflow-tabs" role="tablist" aria-label="Research workflow stages">{#each workflow as step, index}<button class:active={activeStep === index} role="tab" aria-selected={activeStep === index} onclick={() => (activeStep = index)}><span>{step.code}</span><b>{step.title}</b><i>→</i></button>{/each}</div><article class="workflow-panel" aria-live="polite"><span class="panel-index">{workflow[activeStep].code}</span><div><span class="public-eyebrow">{workflow[activeStep].title}</span><h3>{workflow[activeStep].heading}</h3><p>{workflow[activeStep].copy}</p><ul>{#each workflow[activeStep].list as item}<li>{item}</li>{/each}</ul></div></article></div></section>
<section class="public-section evidence-section"><div class="evidence-copy"><span class="public-eyebrow">Designed for the research record</span><h2>Measured, calculated and provisional values do not become the same thing.</h2><p>Every nutrient value stays connected to its evidence lane, unit, food basis, source release and review state. A calculation can consume evidence; it cannot erase where that evidence came from.</p><a href={`${base}/features`}>Read the scientific capability map <span>→</span></a></div><div class="evidence-lanes"><div><span>01</span><b>Historical evidence</b><p>Read-only Java-era source and explicit compatibility calculations.</p><i class="amber"></i></div><div><span>02</span><b>Research core</b><p>Versioned foods, participants, experiments, recalls and imports.</p><i></i></div><div><span>03</span><b>Validated research</b><p>Ontology, provenance, recipes, retention and reviewed mappings.</p><i></i></div></div></section>
<section class="public-cta"><div><span class="public-eyebrow">A lightweight demonstration</span><h2>Test the implemented workflow with synthetic records.</h2><p>Calculate food portions, enter recalls, manage research records and inspect provenance. Licensed ingestion and independent specialist decisions require external evidence or additional verified accounts. The demo resets when its free service restarts.</p></div><a class="public-button light" href={`${base}/projects`}>Enter the demo workspace <span>→</span></a></section>
