<script lang="ts">
  import { onMount } from 'svelte'; import { get, post } from '$lib/api';
  let usage:any=$state(null);let cohorts:any[]=$state([]);let anomalies:any[]=$state([]);let models:any[]=$state([]);let error=$state('');let busy=$state(false);
  let mode=$state('participant_recorded_mean');let groupBy=$state('overall');let minimumDays=$state(2);let minimumGroup=$state(5);let threshold=$state(3.5);
  async function load(){usage=await get('/api/usage');cohorts=await get('/api/analytics/cohort');anomalies=await get('/api/analytics/anomalies');models=await get('/api/analytics/matching-models')}
  onMount(async()=>{try{await load()}catch(e:any){error=e.message}});
  async function runCohort(){busy=true;error='';try{await post('/api/analytics/cohort',{analysis_mode:mode,group_by:groupBy,minimum_days:minimumDays,minimum_group_size:minimumGroup});await load()}catch(e:any){error=e.message}finally{busy=false}}
  async function runAnomaly(){busy=true;error='';try{await post('/api/analytics/anomalies',{threshold});await load()}catch(e:any){error=e.message}finally{busy=false}}
  async function train(){busy=true;error='';try{await post('/api/analytics/matching-models/train',{});await load()}catch(e:any){error=e.message}finally{busy=false}}
  async function apply(uid:string){busy=true;error='';try{await post(`/api/analytics/matching-models/${uid}/apply`,{});await load()}catch(e:any){error=e.message}finally{busy=false}}
</script>
<div class="page-head"><div><span class="kicker">Governed inference</span><h1>Research analytics</h1><p>Run reproducible cohort descriptions and review-only quality models over project-scoped data.</p></div>{#if usage}<span class="status">{usage.calculation_runs.remaining} runs remaining</span>{/if}</div>
<div class="notice warn"><b>Research use only.</b> Recorded-day means are not usual intake. Small groups are suppressed, anomaly flags never change source evidence, and the matching model only prioritizes human review.</div>
{#if error}<div class="error">{error}</div>{/if}
<section class="platform-grid" style="margin-top:16px"><div class="card"><span class="tag">Deterministic EDA</span><h2>Cohort distributions</h2><label>Observation unit <select bind:value={mode}><option value="participant_recorded_mean">Participant recorded-day mean</option><option value="recall_day">Recall day</option></select></label><label>Group by <select bind:value={groupBy}><option value="overall">Overall</option><option value="gender_code">Gender code</option><option value="life_id">Life stage</option><option value="activity_level">Activity</option></select></label><div class="form-grid"><label>Minimum days <input type="number" min="1" bind:value={minimumDays}/></label><label>Suppression n <input type="number" min="5" bind:value={minimumGroup}/></label></div><button class="btn primary" disabled={busy} onclick={runCohort}>Run descriptives</button></div>
<div class="card"><span class="tag">Review-only QC</span><h2>Laboratory anomaly flags</h2><p class="card-sub">Median/MAD robust scores are calculated within nutrient and unit. No value is rejected automatically.</p><label>Robust z threshold <input type="number" min="2" max="10" step="0.1" bind:value={threshold}/></label><button class="btn primary" disabled={busy} onclick={runAnomaly}>Run quality screen</button></div>
<div class="card"><span class="tag">Governed ML</span><h2>Food-match triage</h2><p class="card-sub">Train only from reviewed accepted/rejected candidates. Five-fold metrics are saved; a verified specialist must approve before scoring candidates.</p><button class="btn primary" disabled={busy} onclick={train}>Train candidate model</button></div></section>
<section class="card" style="margin-top:16px"><h2>Saved analysis runs</h2><div class="component-grid"><div class="component"><span class="component-label">Cohort runs</span><b>{cohorts.length}</b><small>{cohorts[0]?.status||'No run yet'}</small></div><div class="component"><span class="component-label">Anomaly runs</span><b>{anomalies.length}</b><small>{anomalies[0]?.flag_count??'No run yet'} latest flags</small></div><div class="component"><span class="component-label">Matching models</span><b>{models.length}</b><small>{models[0]?.review_status||'No model yet'}</small></div></div>{#each models as model}<div class="split" style="margin-top:10px"><span>{model.model_type} · {model.training_count} reviewed labels · {model.review_status}</span>{#if model.review_status==='approved'}<button class="btn" onclick={()=>apply(model.matching_model_uid)}>Prioritize candidates</button>{/if}</div>{/each}</section>
