<script lang="ts">
  import { onMount } from 'svelte'; import { get, post } from '$lib/api';
  let cases:any[]=$state([]);let specialists:any[]=$state([]);let error=$state('');let specialization=$state('food_composition');let credentials=$state('');let email=$state('');
  async function load(){cases=await get('/api/reviews?status=all');specialists=await get('/api/specialists')}
  onMount(async()=>{try{await load()}catch(e:any){error=e.message}});
  async function register(){try{await post('/api/specialists',{email,specialization,credentials,country_code:'NG'});credentials='';await load()}catch(e:any){error=e.message}}
  async function decide(uid:string,decision:string){const rationale=prompt(`Scientific rationale for ${decision}:`)||'';if(!rationale)return;try{await post(`/api/reviews/${uid}/decide`,{decision,rationale,evidence_checked:{checked:true}});await load()}catch(e:any){error=e.message}}
</script>
<div class="page-head"><div><span class="kicker">Independent validation gate</span><h1>Scientific review</h1><p>Provisional ontology, mappings, evidence values, retention factors, source releases and matching models become reviewed only after an independent verified specialist decision.</p></div></div>
{#if error}<div class="error">{error}</div>{/if}
<section class="platform-grid"><div class="card"><h2>Register specialist profile</h2><label>Platform email <input bind:value={email} type="email"/></label><label>Specialization <select bind:value={specialization}><option value="food_composition">Food composition</option><option value="nutritional_biochemistry">Nutritional biochemistry</option><option value="dietary_assessment">Dietary assessment</option><option value="analytical_chemistry">Analytical chemistry</option></select></label><label>Credentials <textarea bind:value={credentials}></textarea></label><button class="btn primary" onclick={register}>Submit for verification</button></div><div class="card"><h2>Specialists</h2>{#each specialists as item}<div class="component"><b>{item.display_name}</b><small>{item.specialization} · {item.status}</small></div>{/each}</div></section>
<section class="card" style="margin-top:16px"><h2>Review queue</h2><div class="table-wrap"><table><thead><tr><th>Target</th><th>Submitted</th><th>Status</th><th>Decision</th></tr></thead><tbody>{#each cases as item}<tr><td><b>{item.target_type}</b><small>{item.target_uid}</small></td><td>{item.submitted_by}<small>{item.submitted_at}</small></td><td><span class="tag">{item.status}</span></td><td>{#if item.status==='pending'}<button class="btn" onclick={()=>decide(item.review_case_uid,'approved')}>Approve</button> <button class="btn" onclick={()=>decide(item.review_case_uid,'rejected')}>Reject</button>{:else}{item.rationale||'—'}{/if}</td></tr>{/each}</tbody></table></div></section>
