<script lang="ts">
 import {onMount} from 'svelte'; import {fileToBase64,get,post} from '$lib/api';
 let file:File|null=$state(null),entity=$state('foods'),policy=$state('reject'),sheet=$state(''),staged:any=$state(null),imports:any[]=$state([]),error=$state(''),message=$state(''),busy=$state(false);
 const entities=[['foods','Research foods'],['participants','Participants'],['app_users','Global identities (advanced)'],['experiments','Experiments'],['components','Legacy food components'],['experiment_results','Experiment results'],['data_sources','Data sources'],['source_releases','Source releases'],['external_foods','External composition foods'],['external_components','External nutrient values'],['validated_components','Validated research nutrient values'],['retention_factors','Cooking retention factors']];
 async function load(){try{imports=await get('/api/imports?limit=30')}catch{}}
 async function stage(){if(!file)return;busy=true;error='';try{staged=await post('/api/imports/stage',{filename:file.name,content_base64:await fileToBase64(file),entity_type:entity,conflict_policy:policy,sheet_name:sheet||undefined});await load()}catch(e:any){error=e.message}finally{busy=false}}
 async function commit(){if(!staged)return;busy=true;try{const r=await post(`/api/imports/${staged.batch_uid}/commit`,{});message=`Batch committed: ${r.inserted||0} inserted, ${r.updated||0} updated.`;staged=null;file=null;await load()}catch(e:any){error=e.message}finally{busy=false}}
 onMount(load);
</script>
<div class="page-head"><div><span class="kicker">Controlled ingestion</span><h1>Batch import</h1><p>CSV and XLSX files are staged and validated before any write occurs. The original file checksum, row-level validation result and final database action are retained.</p></div><a class="btn secondary" href={`/api/templates/csv/${entity}`}>Download CSV template</a></div>
{#if error}<div class="error" style="margin-bottom:12px">{error}</div>{/if}{#if message}<div class="success" style="margin-bottom:12px">{message}</div>{/if}
<div class="grid-2"><div class="card"><h2>1 · Select import</h2><div class="card-sub">Flat research tables only · maximum 25 MiB · quota is charged only when a valid batch commits</div><div class="form-grid"><div class="field"><label>Entity type <select bind:value={entity}>{#each entities as item}<option value={item[0]}>{item[1]}</option>{/each}</select></label></div><div class="field"><label>Conflict policy <select bind:value={policy}><option value="reject">Reject conflicts</option><option value="insert_only">Insert only</option><option value="upsert">Upsert + audit history</option></select></label></div><div class="field span-2"><label>XLSX sheet (optional) <input bind:value={sheet} placeholder="Defaults to the matching template sheet"/></label></div></div><div class="file-drop" style="margin-top:16px"><b style="font-size:12px">CSV or XLSX research data</b><p class="card-sub">Raw files are hashed before staging. Add identities to a workspace from Contributors after importing them.</p><input type="file" accept=".csv,.xlsx" onchange={(e)=>file=(e.currentTarget as HTMLInputElement).files?.[0]||null}/>{#if file}<p class="mono">{file.name} · {(file.size/1024).toFixed(1)} KiB</p>{/if}</div><div class="panel-actions"><button class="btn" disabled={!file||busy} onclick={stage}>{busy?'Validating…':'Stage & validate'}</button></div></div>
<div class="card"><h2>2 · Review before commit</h2><div class="card-sub">No database write to research entities occurs during staging.</div>{#if staged}<div class="component-grid"><div class="component"><span class="component-label">Rows</span><b>{staged.row_count}</b></div><div class="component"><span class="component-label">Valid</span><b>{staged.valid_count}</b></div><div class="component"><span class="component-label">Invalid</span><b>{staged.invalid_count}</b></div><div class="component"><span class="component-label">Policy</span><b>{policy}</b></div></div><div class="table-wrap" style="margin-top:13px"><table class="data-table"><thead><tr><th>Row</th><th>Status</th><th>Validation</th></tr></thead><tbody>{#each staged.preview as row}<tr><td>{row.row_number}</td><td><span class:warn={row.status==='invalid'} class="status">{row.status}</span></td><td>{row.errors.join('; ')||'Ready'}</td></tr>{/each}</tbody></table></div><div class="panel-actions"><button class="btn" disabled={staged.invalid_count>0||busy} onclick={commit}>Commit validated batch</button></div>{:else}<div class="empty">Stage a file to inspect row-level validation.</div>{/if}</div></div>
<div class="card" style="margin-top:18px"><h2>Import history</h2><div class="card-sub">Every staged source remains attributable by checksum.</div><div class="table-wrap"><table class="data-table"><thead><tr><th>File</th><th>Entity</th><th>Rows</th><th>Valid</th><th>Status</th><th>Created</th></tr></thead><tbody>{#each imports as b}<tr><td>{b.source_filename}</td><td>{b.entity_type}</td><td>{b.row_count}</td><td>{b.valid_count}</td><td><span class="status">{b.status}</span></td><td>{b.created_at}</td></tr>{/each}</tbody></table></div></div>
