<script lang="ts">
  import { base } from '$app/paths';
  const plans = [
    { name: 'Student', audience: 'Coursework and supervised projects', allowance: '50', imports: '50 committed import rows', calculations: '50 calculation or inference runs', projects: '1 project · up to 3 members', featured: false },
    { name: 'Independent', audience: 'Individual researchers and small studies', allowance: '100', imports: '100 committed import rows', calculations: '100 calculation or inference runs', projects: 'Up to 3 projects · 8 members each', featured: true },
    { name: 'Research group', audience: 'Labs, cohorts and multi-user programmes', allowance: '100+', imports: 'Contracted import allowance above 100', calculations: 'Contracted calculation allowance above 100', projects: 'Expanded projects, membership and support', featured: false }
  ];
</script>
<svelte:head><title>Research plans · Dietary Recall</title></svelte:head>
<section class="public-page-intro pricing-intro"><span class="public-eyebrow">Freemium research access</span><h1>Scale the allowance,<br/>not the scientific rules.</h1><p>Every plan uses the same provenance, review and audit boundaries. Limits are applied to a project space so its contributors share one reproducible ledger.</p></section>
<section class="pricing-grid">{#each plans as plan}<article class:featured={plan.featured} class="pricing-card">{#if plan.featured}<span class="plan-flag">Best for current research</span>{/if}<span class="plan-name">{plan.name}</span><p>{plan.audience}</p><div class="plan-allowance"><strong>{plan.allowance}</strong><span>imports<br/>and runs / month</span></div><ul><li><i>✓</i>{plan.imports}</li><li><i>✓</i>{plan.calculations}</li><li><i>✓</i>{plan.projects}</li><li><i>✓</i>Versioning, provenance and audit</li></ul><a class="public-button {plan.featured ? 'primary' : 'outline'}" href={`${base}/projects`}>{plan.name === 'Research group' ? 'Preview the platform' : `Start with ${plan.name}`} <span>→</span></a></article>{/each}</section>
<section class="pricing-policy"><div><span class="public-eyebrow">How usage is counted</span><h2>Only completed research actions consume allowance.</h2></div><ul><li>File staging and validation failures do not consume import rows.</li><li>Failed strict recipe calculations do not consume calculation runs.</li><li>Committed rows and saved calculations are recorded atomically.</li><li>Quotas belong to the project, not to individual contributors.</li></ul></section>
<section class="faq-section"><div><span class="public-eyebrow">Research plan questions</span><h2>Before you choose a plan</h2></div><div>{#each [{q:'Does the public demo contain the PhD database?',a:'No. It is generated from deterministic synthetic foods and participants and resets on service restart.'},{q:'Do higher plans change calculation methods?',a:'No. Plans change capacity and collaboration limits; scientific evidence and review rules remain the same.'},{q:'Can a research group exceed the listed allowance?',a:'Yes. Paid entitlements use explicit contractual limits above 100 and are activated only after verified subscription handling.'}] as item}<details><summary>{item.q}<span>+</span></summary><p>{item.a}</p></details>{/each}</div></section>
