<script lang="ts">
  import { base } from '$app/paths';
  import { onMount } from 'svelte';
  import { get, summaryWithFallback } from '$lib/api';
  let summary: any = $state(null); let live = $state(true); let audit: any[] = $state([]);
  const percent = (used: number, limit: number) => limit > 0 ? Math.min(100, (used / limit) * 100) : 0;
  onMount(async () => { const result = await summaryWithFallback(); summary = result.data; live = result.live; if (live) { try { audit = await get('/api/audit?limit=5'); } catch { audit = []; } } });
</script>
<div class="page-head workspace-page-head"><div><span class="kicker">Scientific workspace</span><h1>Project overview</h1><p>Current records, research capacity and provenance activity for the selected study.</p></div><div class="page-head-actions"><a class="btn secondary" href={`${base}/imports`}>Import a batch</a><a class="btn" href={`${base}/foods`}>＋ Add research food</a></div></div>
{#if !live}<div class="offline-banner">The research API is unavailable. Live records and write actions are paused.</div>{/if}
{#if summary}<section class="metric-grid scientific-metrics"><div class="metric"><span>Research foods</span><strong>{summary.foods}</strong><small>Project composition catalog</small></div><div class="metric"><span>Participants</span><strong>{summary.participants}</strong><small>Versioned study identities</small></div><div class="metric"><span>External records</span><strong>{summary.external_foods}</strong><small>Source-release provenance</small></div><div class="metric"><span>Recipes</span><strong>{summary.recipes}</strong><small>{summary.calculation_runs} saved calculation runs</small></div></section>
<section class="grid-2 workspace-overview-grid"><div class="card evidence-foundation"><div class="split"><div><span class="kicker">Validated research</span><h2>Composition foundation</h2><div class="card-sub">Canonical ontology and evidence-aware calculations</div></div><span class="status">Schema v{summary.schema_version}</span></div><div class="allowance-block"><div class="split"><span>Monthly import allowance</span><b>{summary.usage.import_rows.remaining} remaining</b></div><div class="progress"><i style={`width:${percent(summary.usage.import_rows.used,summary.usage.import_rows.limit)}%`}></i></div></div><div class="notice"><b>Evidence lanes remain separate.</b><br/>Measured values are never overwritten, missing nutrients remain missing, and external records retain source-release provenance.</div><div class="component-grid"><div class="component"><span>Canonical nutrients</span><b>{summary.canonical_nutrients}</b></div><div class="component"><span>Accepted matches</span><b>{summary.food_matches}</b></div><div class="component"><span>Current plan</span><b>{summary.usage.plan_name}</b></div><div class="component"><span>Calculation credits</span><b>{summary.usage.calculation_runs.remaining} remaining</b></div></div></div>
<div class="card"><div class="split"><div><span class="kicker">Traceability</span><h2>Recent provenance</h2><div class="card-sub">Latest research data events</div></div><a href={`${base}/audit`} class="btn secondary small">View audit</a></div>{#if audit.length}<div class="timeline">{#each audit as event}<div class="timeline-row"><div class="timeline-line"><i></i></div><div class="timeline-content"><b>{event.action} · {event.entity_type}</b><p>{event.actor} · {event.source}</p><time>{event.created_at}</time></div></div>{/each}</div>{:else}<div class="empty">Audit events appear when records are created, reviewed or calculated.</div>{/if}</div></section>
<section class="workspace-quick-actions"><div><span class="kicker">Continue the study</span><h2>Common research actions</h2></div><div><a href={`${base}/calculator`}><span>CA</span><b>Calculate a food portion</b><i>→</i></a><a href={`${base}/recalls`}><span>RC</span><b>Enter a dietary recall</b><i>→</i></a><a href={`${base}/experiments`}><span>EX</span><b>Record an experiment</b><i>→</i></a></div></section>{/if}
