<script lang="ts">
  import { onMount } from 'svelte';
  import { get, post } from '$lib/api';
  let recipes: any[] = $state([]); let foods: any[] = $state([]); let externalFoods: any[] = $state([]); let nutrients: any[] = $state([]); let releases: any[] = $state([]); let factors: any[] = $state([]); let error = $state(''); let message = $state(''); let result: any = $state(null);
  let recipeForm: any = $state({ recipe_code: '', recipe_name: '', cooking_method_code: 'boiled', final_cooked_weight_g: 500, servings: 4 });
  let ingredients: any[] = $state([{ kind: 'research', food_uid: '', input_weight_g: 100, edible_fraction: 1, food_group: '' }]);
  let retention: any = $state({ source_release_uid: '', cooking_method_code: 'boiled', food_group: '', canonical_nutrient_uid: '', retention_fraction: 1, factor_status: 'reported' });
  async function load() { try { [recipes, foods, externalFoods, nutrients, releases, factors] = await Promise.all([get('/api/recipes'), get('/api/foods?limit=1000'), get('/api/external-foods?limit=1000'), get('/api/ontology'), get('/api/source-releases'), get('/api/retention-factors')]); error = ''; } catch (e: any) { error = e.message; } }
  function addIngredient() { ingredients = [...ingredients, { kind: 'research', food_uid: '', input_weight_g: 100, edible_fraction: 1, food_group: '' }]; }
  function removeIngredient(index: number) { ingredients = ingredients.filter((_, i) => i !== index); }
  async function createRecipe() { try { const payload = { ...recipeForm, ingredients: ingredients.map((item) => ({ research_food_uid: item.kind === 'research' ? item.food_uid : null, external_food_uid: item.kind === 'external' ? item.food_uid : null, input_weight_g: Number(item.input_weight_g), edible_fraction: Number(item.edible_fraction), food_group: item.food_group })) }; await post('/api/recipes', payload); message = 'Recipe saved'; await load(); } catch (e: any) { error = e.message; } }
  async function addRetention() { try { await post('/api/retention-factors', { ...retention, retention_fraction: Number(retention.retention_fraction) }); message = 'Retention factor registered'; await load(); } catch (e: any) { error = e.message; } }
  async function calculate(uid: string, policy: string) { try { result = await post(`/api/recipes/${uid}/calculate`, { policy }); message = `Calculation ${result.validation_status}`; await load(); } catch (e: any) { error = e.message; } }
  onMount(load);
</script>
<div class="page-head"><div><span class="kicker">Yield and true-retention model</span><h1>Recipes & retention</h1><p>Compose research or external foods, record edible input and final cooked weight, apply source-backed retention factors and save a complete calculation snapshot.</p></div></div>
{#if error}<div class="error" style="margin-bottom:12px">{error}</div>{/if}{#if message}<div class="success" style="margin-bottom:12px">{message}</div>{/if}
<section class="grid-2"><div class="card"><h2>New recipe</h2><div class="form-grid"><div class="field"><label>Recipe code <input bind:value={recipeForm.recipe_code} /></label></div><div class="field"><label>Name <input bind:value={recipeForm.recipe_name} /></label></div><div class="field"><label>Cooking method code <input bind:value={recipeForm.cooking_method_code} /></label></div><div class="field"><label>Final cooked weight (g) <input type="number" bind:value={recipeForm.final_cooked_weight_g} /></label></div></div><h2 style="margin-top:18px">Ingredients</h2><div style="display:grid;gap:8px">{#each ingredients as ingredient, index}<div class="recipe-ingredient"><div class="field"><label>Source <select bind:value={ingredient.kind}><option value="research">Research food</option><option value="external">External food</option></select><select bind:value={ingredient.food_uid}><option value="">Select food</option>{#if ingredient.kind === 'research'}{#each foods as food}<option value={food.food_uid}>{food.food_name}</option>{/each}{:else}{#each externalFoods as food}<option value={food.external_food_uid}>{food.food_name}</option>{/each}{/if}</select></label></div><div class="field"><label>Input g <input type="number" bind:value={ingredient.input_weight_g} /></label></div><div class="field"><label>Edible fraction <input type="number" step="0.01" bind:value={ingredient.edible_fraction} /></label></div><button class="btn secondary small" onclick={() => removeIngredient(index)}>Remove</button></div>{/each}</div><div class="panel-actions"><button class="btn secondary" onclick={addIngredient}>＋ Ingredient</button><button class="btn" onclick={createRecipe}>Save recipe</button></div></div>
<div class="card"><h2>Retention factor</h2><div class="card-sub">Factors are fractions: 0.85 means 85% retained.</div><div class="form-grid"><div class="field span-2"><label>Source release <select bind:value={retention.source_release_uid}><option value="">Select release</option>{#each releases as release}<option value={release.source_release_uid}>{release.source_name} · {release.release_label}</option>{/each}</select></label></div><div class="field"><label>Cooking method <input bind:value={retention.cooking_method_code} /></label></div><div class="field"><label>Food group (optional) <input bind:value={retention.food_group} /></label></div><div class="field"><label>Nutrient <select bind:value={retention.canonical_nutrient_uid}><option value="">Select nutrient</option>{#each nutrients as nutrient}<option value={nutrient.canonical_nutrient_uid}>{nutrient.display_name}</option>{/each}</select></label></div><div class="field"><label>Retention fraction <input type="number" min="0" max="1" step="0.01" bind:value={retention.retention_fraction} /></label></div></div><div class="panel-actions"><button class="btn" onclick={addRetention}>Register factor</button></div><div class="notice warn">Strict runs stop if any required nutrient factor is absent. Best-available runs may assume 1.0, but are saved as exploratory with a warning.</div></div></section>
<div class="card" style="margin-top:18px"><h2>Recipe catalogue</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Recipe</th><th>Method</th><th>Final weight</th><th>Ingredients</th><th>Status</th><th>Calculate</th></tr></thead><tbody>{#each recipes as recipe}<tr><td><b>{recipe.recipe_name}</b><br/><span class="mono">{recipe.recipe_code}</span></td><td>{recipe.cooking_method_code}</td><td>{recipe.final_cooked_weight_g} g</td><td>{recipe.ingredient_count}</td><td>{recipe.status}</td><td><button class="btn secondary small" onclick={() => calculate(recipe.recipe_uid, 'strict')}>Strict</button> <button class="btn small" onclick={() => calculate(recipe.recipe_uid, 'best_available')}>Best available</button></td></tr>{/each}</tbody></table></div></div>
<div class="card" style="margin-top:18px"><h2>Registered retention factors</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Method</th><th>Food group</th><th>Nutrient</th><th>Fraction</th><th>Evidence</th><th>Source release</th></tr></thead><tbody>{#each factors as factor}<tr><td class="mono">{factor.cooking_method_code}</td><td>{factor.food_group || 'All groups'}</td><td>{factor.display_name}</td><td>{factor.retention_fraction}</td><td><span class="tag">{factor.factor_status}</span></td><td>{factor.source_name} · {factor.release_label}</td></tr>{/each}</tbody></table></div></div>
{#if result}<div class="card" style="margin-top:18px"><div class="split"><div><h2>{result.recipe_name} result</h2><div class="card-sub">Snapshot {result.input_snapshot_hash}</div></div><span class:warn={result.validation_status !== 'validated'} class="status">{result.validation_status}</span></div>{#each result.warnings as warning}<div class="notice warn" style="margin-bottom:7px">{warning}</div>{/each}<div class="table-wrap"><table class="data-table"><thead><tr><th>Nutrient</th><th>Total recipe</th><th>Per 100 g</th><th>Retention status</th></tr></thead><tbody>{#each result.results as row}<tr><td>{row.display_name}</td><td>{row.total_recipe_value.toFixed(4)} {row.unit}</td><td>{row.per_100g_value.toFixed(4)} {row.unit}</td><td>{row.retention_status}</td></tr>{/each}</tbody></table></div></div>{/if}
