<script lang="ts">
  import { onMount } from 'svelte'; import { get, post, put } from '$lib/api';
  let rows:any[]=$state([]), query=$state(''), show=$state(false), selected:any=$state(null), error=$state(''), message=$state('');
  let form:any=$state({participant_code:'',surname:'',firstname:'',age_years:'',gender_code:'',activity_level:'',life_id:'',notes:''});
  const reset=()=>form={participant_code:'',surname:'',firstname:'',age_years:'',gender_code:'',activity_level:'',life_id:'',notes:''};
  async function load(){try{rows=await get(`/api/participants?q=${encodeURIComponent(query)}&limit=250`)}catch(e:any){error=e.message}}
  async function create(){try{const p=await post('/api/participants',form);message=`Created participant ${p.participant_code}`;show=false;reset();await load()}catch(e:any){error=e.message}}
  function edit(p:any){selected=p;show=true;form={participant_code:p.participant_code,surname:p.surname||'',firstname:p.firstname||'',age_years:p.age_years??'',gender_code:p.gender_code||'',activity_level:p.activity_level||'',life_id:p.life_id??'',notes:p.notes||''}}
  async function save(){try{const p=await put(`/api/participants/${selected.participant_uid}`,form);message=`Saved ${p.participant_code} version ${p.version}`;show=false;selected=null;await load()}catch(e:any){error=e.message}}
  onMount(load);
</script>
<div class="page-head"><div><span class="kicker">Research identities</span><h1>Participant manager</h1><p>Manage study participants independently from application accounts. Legacy Usercodes remain provenance keys; new studies receive platform participant codes.</p></div><button class="btn" onclick={()=>{selected=null;reset();show=true}}>＋ New participant</button></div>
{#if error}<div class="error" style="margin-bottom:12px">{error}</div>{/if}{#if message}<div class="success" style="margin-bottom:12px">{message}</div>{/if}
<div class="card"><div class="toolbar"><div class="search"><input bind:value={query} onkeydown={(e)=>e.key==='Enter'&&load()} placeholder="Participant code, legacy code or name…"/></div><button class="btn secondary" onclick={load}>Search</button><span class="status neutral">{rows.length} shown</span></div>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Participant code</th><th>Legacy ID</th><th>Age</th><th>Activity</th><th>Life stage ID</th><th>Version</th></tr></thead><tbody>{#each rows as p}<tr onclick={()=>edit(p)} style="cursor:pointer"><td class="mono">{p.participant_code}</td><td>{p.legacy_usercode??'—'}</td><td>{p.age_years??'—'}</td><td>{p.activity_level??'—'}</td><td>{p.life_id??'—'}</td><td>v{p.version}</td></tr>{/each}</tbody></table></div></div>
{#if show}<div class="drawer-backdrop"><section class="drawer"><div class="drawer-head"><div><span class="kicker">{selected?'Versioned update':'New research identity'}</span><h2>{selected?selected.participant_code:'Add participant'}</h2></div><button class="close" onclick={()=>show=false}>×</button></div>
<div class="form-grid"><div class="field"><label>Participant code <input bind:value={form.participant_code} placeholder="Auto if blank"/></label></div><div class="field"><label>Age (years) <input type="number" bind:value={form.age_years}/></label></div><div class="field"><label>Surname <input bind:value={form.surname}/></label></div><div class="field"><label>Firstname <input bind:value={form.firstname}/></label></div><div class="field"><label>Gender code <input bind:value={form.gender_code}/></label></div><div class="field"><label>Activity level <input bind:value={form.activity_level}/></label></div><div class="field"><label>Life stage ID <input type="number" bind:value={form.life_id}/></label></div><div class="field span-2"><label>Research notes <textarea bind:value={form.notes}></textarea></label></div></div>
<div class="notice" style="margin-top:14px">Application users are managed separately. This record represents a research participant, not a login account.</div><div class="panel-actions"><button class="btn secondary" onclick={()=>show=false}>Cancel</button><button class="btn" onclick={selected?save:create}>{selected?'Save new version':'Create participant'}</button></div></section></div>{/if}

