<script lang="ts">
  import { onMount } from 'svelte';
  import { get, post, put } from '$lib/api';

  let foods: any[] = $state([]), nutrients: any[] = $state([]), canonical: any[] = $state([]), releases: any[] = $state([]), query = $state(''), loading = $state(true);
  let selected: any = $state(null), showCreate = $state(false), error = $state(''), message = $state('');
  let form: any = $state({ food_name:'', description:'', preparation_method:'', category:'' });
  let component: any = $state({ nutrient_code:'', value:'', value_status:'measured', source_type:'research_core' });
  let validated: any = $state({ canonical_nutrient_uid:'', value:'', unit:'', evidence_class:'study_measured', validation_status:'provisional', source_release_uid:'', source_record_uid:'' });
  let nextId = $state<number|null>(null);

  async function loadFoods() { loading=true; try { foods=await get(`/api/foods?q=${encodeURIComponent(query)}&limit=200`); } catch(e:any){error=e.message} finally{loading=false} }
  async function loadMeta() { try { [nutrients, canonical, releases] = await Promise.all([get('/api/nutrients'), get('/api/ontology'), get('/api/source-releases')]); nextId=(await get('/api/foods/next-id')).next_legacy_food_id; } catch {} }
  async function openFood(uid:string){ try{ selected=await get(`/api/foods/${uid}`); form={food_name:selected.food_name,description:selected.description||'',preparation_method:selected.preparation_method||'',category:selected.category||''}; }catch(e:any){error=e.message} }
  async function createFood(){ error=''; try{const made=await post('/api/foods',form); message=`Created ${made.food_name} as Food ID ${made.legacy_food_id}`; showCreate=false; form={food_name:'',description:'',preparation_method:'',category:''}; await loadFoods(); await loadMeta();}catch(e:any){error=e.message} }
  async function updateFood(){ try{selected=await put(`/api/foods/${selected.food_uid}`,form); message='Food metadata version saved.'; await loadFoods()}catch(e:any){error=e.message} }
  async function saveComponent(){ if(!component.nutrient_code)return; try{await post(`/api/foods/${selected.food_uid}/components`,component); selected=await get(`/api/foods/${selected.food_uid}`); component={nutrient_code:'',value:'',value_status:'measured',source_type:'research_core'}; message='Component value saved with provenance.';}catch(e:any){error=e.message} }
  function selectCanonical(uid:string){const nutrient=canonical.find((item)=>item.canonical_nutrient_uid===uid);validated.canonical_nutrient_uid=uid;validated.unit=nutrient?.canonical_unit||'';}
  async function saveValidated(){if(!validated.canonical_nutrient_uid)return;try{await post(`/api/foods/${selected.food_uid}/validated-components`,validated);selected=await get(`/api/foods/${selected.food_uid}`);validated={canonical_nutrient_uid:'',value:'',unit:'',evidence_class:'study_measured',validation_status:'provisional',source_release_uid:'',source_record_uid:''};message='Validated-layer evidence added without replacing legacy composition.';}catch(e:any){error=e.message}}
  onMount(async()=>{await Promise.all([loadFoods(),loadMeta()])});
</script>

<div class="page-head"><div><span class="kicker">Curated research master</span><h1>Food manager</h1><p>Add Nigerian prepared foods, edit research metadata and maintain explicit composition values without changing the historical SQLite evidence.</p></div><button class="btn" onclick={()=>{showCreate=true;selected=null;form={food_name:'',description:'',preparation_method:'',category:''}}}>＋ New food</button></div>
{#if error}<div class="error" style="margin-bottom:12px">{error}</div>{/if}{#if message}<div class="success" style="margin-bottom:12px">{message}</div>{/if}
<div class="card">
  <div class="toolbar"><div class="search"><input bind:value={query} onkeydown={(e)=>e.key==='Enter'&&loadFoods()} placeholder="Search food name or legacy ID…" /></div><button class="btn secondary" onclick={loadFoods}>Search</button><span class="status neutral">Next ID: {nextId ?? '—'}</span></div>
  <div class="table-wrap"><table class="data-table"><thead><tr><th>Food ID</th><th>Food name</th><th>Preparation</th><th>Coverage</th><th>Source</th><th>Version</th></tr></thead><tbody>
    {#each foods as food}<tr onclick={()=>openFood(food.food_uid)} style="cursor:pointer"><td class="mono">{food.legacy_food_id}</td><td><b>{food.food_name}</b></td><td>{food.preparation_method||'—'}</td><td>{food.reported_components}/{food.total_components}</td><td><span class="tag">{food.source_scope}</span></td><td>v{food.version}</td></tr>{/each}
  </tbody></table>{#if loading}<div class="empty">Loading research foods…</div>{:else if !foods.length}<div class="empty">No foods match this search.</div>{/if}</div>
</div>

{#if showCreate}
<div class="drawer-backdrop" role="presentation"><section class="drawer" aria-label="Create food"><div class="drawer-head"><div><span class="kicker">Food ID {nextId}</span><h2>Add research food</h2><p class="card-sub">The ID is allocated transactionally when you save.</p></div><button class="close" onclick={()=>showCreate=false}>×</button></div>
  <div class="form-grid"><div class="field span-2"><label>Food name * <input bind:value={form.food_name}/></label></div><div class="field"><label>Preparation <input bind:value={form.preparation_method} placeholder="e.g. cooked, fried"/></label></div><div class="field"><label>Category <input bind:value={form.category}/></label></div><div class="field span-2"><label>Description <textarea bind:value={form.description}></textarea></label></div></div><div class="notice" style="margin-top:14px">Composition is added after the food identity is created, so every measurement has a stable food UID and audit history.</div><div class="panel-actions"><button class="btn secondary" onclick={()=>showCreate=false}>Cancel</button><button class="btn" onclick={createFood}>Create food</button></div>
</section></div>{/if}

{#if selected}
<div class="drawer-backdrop"><section class="drawer"><div class="drawer-head"><div><span class="kicker">Food ID {selected.legacy_food_id} · v{selected.version}</span><h2>{selected.food_name}</h2><p class="card-sub mono">{selected.food_uid}</p></div><button class="close" onclick={()=>selected=null}>×</button></div>
  <h2 style="font-family:inherit;font-size:13px">Research metadata</h2><div class="form-grid"><div class="field span-2"><label>Food name <input bind:value={form.food_name}/></label></div><div class="field"><label>Preparation <input bind:value={form.preparation_method}/></label></div><div class="field"><label>Category <input bind:value={form.category}/></label></div><div class="field span-2"><label>Description <textarea bind:value={form.description}></textarea></label></div></div><div class="panel-actions"><button class="btn" onclick={updateFood}>Save new version</button></div>
  <hr style="border:0;border-top:1px solid #dce4df;margin:24px 0"/><h2 style="font-family:inherit;font-size:13px">Composition</h2><div class="card-sub">Reported/missing provenance remains explicit. Values use the legacy per-100 g basis in this layer.</div>
  <div class="form-grid"><div class="field span-2"><label>Component <select bind:value={component.nutrient_code}><option value="">Select component…</option>{#each nutrients as n}<option value={n.nutrient_code}>{n.component_group} · {n.display_name} ({n.unit})</option>{/each}</select></label></div><div class="field"><label>Value <input type="number" step="any" bind:value={component.value}/></label></div><div class="field"><label>Status <select bind:value={component.value_status}><option>measured</option><option>reported</option><option>missing</option><option>derived</option><option>external_reference</option></select></label></div></div><div class="panel-actions"><button class="btn secondary" onclick={saveComponent}>Add / update component</button></div>
  <div class="component-grid" style="margin-top:14px">{#each selected.components.filter((c:any)=>c.value!==null).slice(0,30) as c}<div class="component"><span class="component-label">{c.display_name}</span><b>{c.value} {c.unit}</b><br/><span class="tag">{c.value_status}</span></div>{/each}</div>
  <hr style="border:0;border-top:1px solid #dce4df;margin:24px 0"/><h2 style="font-family:inherit;font-size:13px">Validated evidence lane</h2><div class="card-sub">Adds a separate canonical value with evidence and review state. It never overwrites the legacy component above.</div>
  <div class="form-grid"><div class="field span-2"><label>Canonical nutrient <select value={validated.canonical_nutrient_uid} onchange={(event)=>selectCanonical(event.currentTarget.value)}><option value="">Select canonical nutrient…</option>{#each canonical as n}<option value={n.canonical_nutrient_uid}>{n.component_class} · {n.display_name} ({n.canonical_unit})</option>{/each}</select></label></div><div class="field"><label>Value <input type="number" step="any" bind:value={validated.value}/></label></div><div class="field"><label>Unit <input bind:value={validated.unit}/></label></div><div class="field"><label>Evidence class <select bind:value={validated.evidence_class}><option value="study_measured">Study measured</option><option value="nigerian_regional">Nigerian regional</option><option value="external_matched">External matched</option><option value="transparent_imputation">Transparent imputation</option><option value="missing">Explicit missing</option></select></label></div><div class="field"><label>Review state <select bind:value={validated.validation_status}><option value="provisional">Provisional</option><option value="reviewed">Reviewed</option><option value="validated">Validated</option><option value="rejected">Rejected</option></select></label></div><div class="field span-2"><label>Source release <select bind:value={validated.source_release_uid}><option value="">Study measurement / no external release</option>{#each releases as release}<option value={release.source_release_uid}>{release.source_name} · {release.release_label}</option>{/each}</select></label></div><div class="field span-2"><label>Source row ID <input bind:value={validated.source_record_uid} placeholder="Optional source record key"/></label></div></div><div class="panel-actions"><button class="btn secondary" onclick={saveValidated}>Add evidence row</button></div>
  {#if selected.accepted_external_match}<div class="notice" style="margin-top:12px">Accepted match: <b>{selected.accepted_external_match.external_food_name}</b> · {selected.accepted_external_match.source_name} {selected.accepted_external_match.release_label}</div>{/if}
  <div class="component-grid" style="margin-top:14px">{#each selected.validated_components || [] as c}<div class="component"><span class="component-label">{c.display_name}</span><b>{c.value === null ? 'missing' : `${c.value} ${c.unit}`}</b><br/><span class="tag">{c.evidence_class} · {c.validation_status}</span></div>{/each}</div>
</section></div>{/if}
