<script lang="ts">
  import { onMount } from 'svelte';
  import { get, post } from '$lib/api';
  let rows: any[] = $state([]); let units: any[] = $state([]); let q = $state(''); let error = $state(''); let converted: any = $state(null);
  let form: any = $state({ value: 1, from_unit: 'mg', to_unit: 'mcg' });
  async function load() { try { rows = await get(`/api/ontology?q=${encodeURIComponent(q)}`); units = await get('/api/units'); } catch (e: any) { error = e.message; } }
  async function convert() { try { converted = await post('/api/units/convert', form); error = ''; } catch (e: any) { error = e.message; } }
  onMount(load);
</script>
<div class="page-head"><div><span class="kicker">Canonical scientific vocabulary</span><h1>Nutrient ontology</h1><p>Legacy columns map to explicit canonical nutrients, expression units and optional INFOODS tagnames without changing historical values.</p></div><span class="status warn">Provisional review queue</span></div>
{#if error}<div class="error" style="margin-bottom:12px">{error}</div>{/if}
<section class="grid-2"><div class="card"><div class="toolbar"><div class="search"><input bind:value={q} onkeydown={(e) => e.key === 'Enter' && load()} placeholder="Search code, name or INFOODS tag" /></div><button class="btn secondary" onclick={load}>Search</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Nutrient</th><th>Class</th><th>Unit</th><th>INFOODS</th><th>Status</th><th>Mappings</th></tr></thead><tbody>{#each rows as nutrient}<tr><td><b>{nutrient.display_name}</b><br/><span class="mono">{nutrient.canonical_code}</span></td><td>{nutrient.component_class}</td><td>{nutrient.canonical_unit}</td><td>{nutrient.infoods_tag || '—'}</td><td><span class:warn={nutrient.ontology_status === 'provisional'} class="status">{nutrient.ontology_status}</span></td><td>{nutrient.mapping_count}</td></tr>{/each}</tbody></table></div></div>
<div class="card"><h2>Unit normalization</h2><div class="card-sub">Only conversions within a compatible physical dimension are automatic.</div><div class="form-grid"><div class="field"><label>Value <input type="number" bind:value={form.value} /></label></div><div></div><div class="field"><label>From <select bind:value={form.from_unit}>{#each units as unit}<option value={unit.unit_code}>{unit.unit_code} · {unit.quantity_dimension}</option>{/each}</select></label></div><div class="field"><label>To <select bind:value={form.to_unit}>{#each units as unit}<option value={unit.unit_code}>{unit.unit_code} · {unit.quantity_dimension}</option>{/each}</select></label></div></div><div class="panel-actions"><button class="btn" onclick={convert}>Convert</button></div>{#if converted}<div class="success">{converted.input_value} {converted.from_unit} = {converted.value} {converted.to_unit}</div>{/if}<div class="notice warn" style="margin-top:14px">IU, RAE and RE are deliberately not converted through a generic formula. Nutrient-specific chemistry and evidence must be supplied.</div></div></section>

